---
# tasks file for vim

- name: Debug var
  debug:
    var: ansible_os_family

- include_tasks: setupMacos.yml
  when: ansible_os_family == "Darwin"

- include_tasks: setupRedHat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: setupDebian.yml
  when: ansible_os_family == "Debian"

- name: make dir for pathogen
  file:
    path: "{{ pathogen_dir }}" 
    state: directory

- name: Download pathogen
  get_url:
    url: "{{ pathogen_url }}" 
    dest: "{{ pathogen_dir }}" 

- name: Clone plugin
  git: 
    repo: "{{ nerdtree_repo }}" 
    dest: "{{ nerdtree_dest }}" 

- name: Clone solarized
  git:
    repo: "{{ solarized_src }}"
    dest: "{{ solarized_dest }}"

- name: Clone summerfruit256
  git:
    repo: "{{ summerfruit_src }}"
    dest: "{{ summerfruit_dest }}"

- name: Clone Indent guides
  git:
    repo: "{{ indentguides_src }}"
    dest: "{{ indentguides_dest }}"

- name: Clone qml syntax
  git:
    repo: "{{ qml_src }}"
    dest: "{{ qml_dest }}"

- name: Check if pass installed
  stat:
    path: "{{ pass_src }}"
  register: pass_installed

- name: Make dir for pass plugin
  file:
    path: "{{ pass_dest }}"
    state: directory
  when: pass_installed.stat.exists

- name: Copy pass plugin
  command: >
    cp "{{ pass_src }}" "{{ pass_dest }}"
  args:
    creates: $HOME/.vim/bundle/pass/plugin/redact_pass.vim
  when: pass_installed.stat.exists

- name: check if vimrc exists
  stat: 
    path: "{{ vimrc_dest }}"
  register: vimrcexists

- name: backupvimrc
  command: >
    cp $HOME/.vimrc $HOME/vimrc.bak
  args:
    creates: $HOME/vimrc.bak
  when: vimrcexists.stat.exists

- name: copy vim.rc
  copy:
    src: "{{ vimrc_src }}"
    dest: "{{ vimrc_dest }}"
